### ISSUE TITLE
No Http Response

### ISSUE THREAD

**Issue by PoDaMo** [dynaptico/pamfaxp#3]
Hello 
I got an error

`Traceback (most recent call last):
  File "D:/Python/wache/testfax.py", line 23, in <module>
    pamfax.send()
  File "C:\Users\Tobi\AppData\Local\Programs\Python\Python38\lib\site-packages\pamfax\processors\__init__.py", line 717, in send
    return _get(self.http, url)
  File "C:\Users\Tobi\AppData\Local\Programs\Python\Python38\lib\site-packages\pamfax\processors\__init__.py", line 104, in _get
    return _get_and_check_response(http)
  File "C:\Users\Tobi\AppData\Local\Programs\Python\Python38\lib\site-packages\pamfax\processors\__init__.py", line 87, in _get_and_check_response
    response = http.getresponse()
  File "C:\Users\Tobi\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\Tobi\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Tobi\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response`

**Comment by bufemc** [comment]
Hello, as I see you tried to run this code - which is meant for Python 2 - on Python 3.8. Maybe you could give it a try with my rewrite for Python 3.6+, which is located at:

https://github.com/bufemc/a1pamfax

or install it by:

```pip install a1pamfax```

Otherwise the behavior should be exactly the same, all public methods and signatures were kept as is on purpose.
